### ISSUE TITLE
Mismatch global Minor Allele Frequency

### ISSUE THREAD

**Issue by SamGLZ** [Illumina/Nirvana#33]
Hi all, 
I found a result of the global Minor Allele Frequency result which may be a mismatch when I annotated an indel variant with Nirvana. The returned result belongs to the next base. What I can do to make it right?

The variant I annotated:
GRCh37: 
1:46736380 T>TCGAGACGCTGCTGCTAGTGAGGCAGACAGGCAGCTAGGAGAGGAGCGGCTGCGGGAGCTCACCAGCATTGTGAATAGGTAATGACCTTAAGC

The result of globalMinorAlleleFrequency is 0.0001997, which belongs to 1:46736381-T (ref: C). And 1:46736380 has no global Minor Allele Frequency and no record in 1000 Genome Project. 

Thank you!

**Comment by rajatshuvro** [comment]
Hi Sam,
Nirvana trims common bases from ref and alt allele (e.g. padding bases) and left shifts the variants in order to ensure proper matching across different equivalent representations. As a result, for the insertions you cited, the position is incremented by 1 and the global minor frequency for 1:46736381 is reported. This is according to our design. 

However, while calculating GMAF, we only considered SNVs. So, you can disregard it for anything other than SNVs.

Hope that helps
Rajat
