### ISSUE TITLE
TestNirvana.sh 

### ISSUE THREAD

**Issue by camtorbri** [Illumina/Nirvana#34]
Love Nirvana annotation and the TestNirvana.sh makes the installation totally painless....!

[Installing in Win10] The very last command in the script:

# analyze it with Nirvana
dotnet $NIRVANA_BIN -c $CACHE_DIR/Both --sd $SA_DIR -r $REF_TEST -i HiSeq.10000.vcf -o HiSeq.10000.annotated

hits an error that is related to a "tab" that should not be there after NA12878 [Line 36 of the HiSeek.1000.vcf].  The extra character maskes it appear as if there is a second sample to follow triggering the error.

ERROR: Inconsistent number of sample fields in line: chr1    109   ..........

Remove the extra tab at the end of this line and the command would run fine.

camilo

**Comment by jerryliu2005** [comment]
Unrelated to the above issue but I want to point out a minor bug with TestNirvana.sh. Between line #80 and #81 you need to add a `cd $NIRVANA_ROOT` statement for `git checkout $NIRVANA_TAG` to work. Otherwise the test script will always run the master branch instead of the release tag. 

Another trivial thing is I do not see where the download() function is used in the test bash script but this doesn't affect anything.

-Jerry

**Comment by camtorbri** [comment]
Thanks...!

**Comment by MichaelStromberg** [comment]
Ah yes, TestNirvana.sh needs some TLC. I'll update that today and ping this thread when complete.

**Comment by MichaelStromberg** [comment]
TestNirvana.sh finally received some TLC today. Thank you for the heads up!
Here's the new page: https://illumina.github.io/NirvanaDocumentation/introduction/getting-started
